# Generated by Django 4.2.9 on 2026-01-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stt", models.IntegerField(unique=True)),
                ("don_vi", models.CharField(max_length=200)),
                ("loai", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ward",
                "ordering": ["stt"],
            },
        ),
        migrations.CreateModel(
            name="Bieu4CTThanhPho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stt", models.IntegerField(verbose_name="STT")),
                ("don_vi", models.CharField(max_length=500, verbose_name="Đơn vị")),
                (
                    "cong_nhan_moi",
                    models.IntegerField(default=0, verbose_name="Công nhận mới"),
                ),
                (
                    "cong_nhan_lai",
                    models.IntegerField(default=0, verbose_name="Công nhận lại"),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "loai",
                    models.CharField(
                        choices=[
                            ("THANH_PHO", "Thành phố"),
                            ("PHUONG", "Phường"),
                            ("XA", "Xã"),
                            ("THI_TRAN", "Thị trấn"),
                        ],
                        default="PHUONG",
                        max_length=20,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Nhập thủ công"),
                            ("adjusted", "Đã chỉnh sửa"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bieu4_records",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "db_table": "bieu4_ct_thanh_pho",
                "ordering": ["stt"],
            },
        ),
        migrations.CreateModel(
            name="Bieu3KH20262030",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phuong_xa",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Phường, xã"
                    ),
                ),
                (
                    "ten_truong",
                    models.CharField(max_length=300, verbose_name="Tên trường"),
                ),
                ("cap_hoc", models.CharField(max_length=100, verbose_name="Cấp học")),
                (
                    "loai_hinh",
                    models.CharField(max_length=10, verbose_name="Loại hình"),
                ),
                (
                    "nam_dat_cqg_gan_nhat",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Năm đạt CQG gần nhất",
                    ),
                ),
                (
                    "cn_moi_2026",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN mới 2026"
                    ),
                ),
                (
                    "cn_moi_2027",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN mới 2027"
                    ),
                ),
                (
                    "cn_moi_2028",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN mới 2028"
                    ),
                ),
                (
                    "cn_moi_2029",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN mới 2029"
                    ),
                ),
                (
                    "cn_moi_2030",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN mới 2030"
                    ),
                ),
                (
                    "cn_lai_2026",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN lại 2026"
                    ),
                ),
                (
                    "cn_lai_2027",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN lại 2027"
                    ),
                ),
                (
                    "cn_lai_2028",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN lại 2028"
                    ),
                ),
                (
                    "cn_lai_2029",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN lại 2029"
                    ),
                ),
                (
                    "cn_lai_2030",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CN lại 2030"
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "ty_le_dat_cqg",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tỷ lệ đạt CQG hết năm 2030",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("import", "Import từ Excel"),
                            ("manual", "Nhập thủ công"),
                            ("adjusted", "Đã chỉnh sửa"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bieu3_records",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "db_table": "bieu3_kh2026_2030",
                "ordering": ["ward__stt", "id"],
            },
        ),
        migrations.CreateModel(
            name="Bieu2KH2026",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phuong_xa",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Phường, xã"
                    ),
                ),
                (
                    "ten_truong",
                    models.CharField(max_length=300, verbose_name="Tên trường"),
                ),
                ("cap_hoc", models.CharField(max_length=100, verbose_name="Cấp học")),
                (
                    "loai_hinh",
                    models.CharField(max_length=10, verbose_name="Loại hình"),
                ),
                (
                    "nam_dat_cqg_gan_nhat",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Năm đạt CQG gần nhất",
                    ),
                ),
                (
                    "phuong_xa_da_kiem_tra",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Phường xã đã kiểm tra",
                    ),
                ),
                (
                    "du_kien_thang",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dự kiến tháng đề nghị TP đánh giá",
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "loai_cong_nhan",
                    models.CharField(
                        choices=[
                            ("CN_MOI", "Công nhận mới"),
                            ("CN_LAI", "Công nhận lại"),
                        ],
                        max_length=20,
                        verbose_name="Loại công nhận",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("import", "Import từ Excel"),
                            ("manual", "Nhập thủ công"),
                            ("adjusted", "Đã chỉnh sửa"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bieu2_records",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "db_table": "bieu2_kh2026",
                "ordering": ["ward__stt", "loai_cong_nhan", "id"],
            },
        ),
        migrations.CreateModel(
            name="Bieu1KQ2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quan_huyen",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Quận, Huyện",
                    ),
                ),
                (
                    "phuong_xa",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Phường, xã"
                    ),
                ),
                (
                    "ten_truong",
                    models.CharField(max_length=300, verbose_name="Tên trường"),
                ),
                ("cap_hoc", models.CharField(max_length=100, verbose_name="Cấp học")),
                (
                    "loai_hinh",
                    models.CharField(max_length=10, verbose_name="Loại hình"),
                ),
                (
                    "nam_dat_chuan_gan_nhat",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Năm đạt chuẩn gần nhất",
                    ),
                ),
                (
                    "muc_do_cqg",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Mức độ CQG"
                    ),
                ),
                (
                    "so_quyet_dinh_cqg",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Số quyết định CQG",
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "loai_cong_nhan",
                    models.CharField(
                        choices=[
                            ("CN_MOI", "Công nhận mới"),
                            ("CN_LAI", "Công nhận lại"),
                        ],
                        max_length=20,
                        verbose_name="Loại công nhận",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("import", "Import từ Excel"),
                            ("manual", "Nhập thủ công"),
                            ("adjusted", "Đã chỉnh sửa"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bieu1_records",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "db_table": "bieu1_kq2025",
                "ordering": ["ward__stt", "loai_cong_nhan", "id"],
            },
        ),
    ]
